defaults: &defaults
  <<: *defaults
  database_id: 
  database_name: 
  gogeo:
    api_url: https://api.gogeo.io/v1
    map_url: https://maps.gogeo.io
    api_key: 
    map_key: 
  logger:
    name: gogeo-showcase
    level: debug
    appenders:
      stdout: true
      file: ./gogeo-showcase.log

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  logger:
    appenders:
      file: /var/log/gogeo-showcase.log