defaults: &defaults
  <<: *defaults
  gogeo_api: app.gogeo.io
  gogeo_map: maps.gogeo.io
  database_id: 
  database_name: 
  collection_id: 
  map_config:
    host: 
  apikey: 
  mapkey: 
  logger:
    name: showcase
    level: debug
    appenders:
      stdout: true
      file: ./showcase.log

development:
  <<: *defaults
  gogeo_api: localhost:9292
  gogeo_map: localhost:9090

test:
  <<: *defaults

production:
  <<: *defaults