defaults: &defaults
  <<: *defaults
  gogeo_api: app.gogeo.io
  gogeo_map: maps.gogeo.io

development:
  <<: *defaults
  gogeo_api: localhost:9292
  gogeo_map: localhost:9090
  database_id: 5267d3d5a7f454fe57000001
  collection_id: 527a1253a7f454accc000002
  # 52779187a7f454777b000001
  apikey: f7c465ef-2bc8-4977-9bb9-3528e4030e8e
  mapkey: 169476c3-09d5-4ec5-974d-fee9a01dac08

test:
  <<: *defaults

production:
  <<: *defaults