source 'https://rubygems.org'

gem 'grape'
gem 'settingslogic'
gem 'json'

gem 'rest-client'
gem 'builder', '~> 3.1.0'
gem 'rack-server-pages', :require => 'rack-server-pages'
# gem "rack-contrib", :git => "https://github.com/rack/rack-contrib.git", :require => "rack/contrib"

group :development do
  gem 'guard'
  gem 'guard-rack'
  gem 'rack-aggregate', :require => 'rack/aggregate'
end

group :test do

end
